let productionSequenceFilter='';
const expandedCorrectionIds=new Set();
function excelDate(value){if(typeof value==='number'){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return d.toLocaleDateString('pt-BR',{timeZone:'UTC'});}return value?String(value):'Data não informada';}
function seqNumber(value){const n=Number(String(value??'').replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:null;}
function sequenceKey(tool,sequence){const n=seqNumber(sequence);return `${String(tool||'').toUpperCase()}|${n??''}`;}
function sequenceLabel(tool,sequence){const n=seqNumber(sequence);return `${tool} · SEQ. ${n==null?'—':String(n).padStart(2,'0')}`;}
const technicalLabels={'Produt':'Produtividade','Qt.Liq':'Quantidade líquida','Efic(%)':'Eficiência','Qt.Bruta':'Quantidade bruta','Hrs.Forno':'Horas de forno','Qt.Tarugo':'Quantidade de tarugos','Tar.Ideal':'Tarugo ideal','Cod.Parada':'Código da parada','Temp.Ferr.':'Temperatura da ferramenta','Temp.Tarugo.':'Temperatura do tarugo','Data Correção':'Data da correção'};
function technicalValue(key,value){if(value===null||value===undefined||String(value).trim()==='')return 'Não informado';if(key.toLocaleLowerCase('pt-BR').includes('data'))return excelDate(value);if(typeof value==='number')return value.toLocaleString('pt-BR',{maximumFractionDigits:2});return String(value).trim();}
function technicalGrid(p){const hidden=new Set(['Descrição','Obs do Lote','Correção Efetuada','Data','Lote','Corretor','Inspetor','Ferramenta','Nr.Correção']);return Object.entries(p).filter(([k])=>!hidden.has(k)).map(([k,v])=>`<div class="technical-item"><span>${esc(technicalLabels[k]||k)}</span><strong>${esc(technicalValue(k,v))}${k==='Efic(%)'&&v!==null&&v!==''?'%':''}</strong></div>`).join('');}
function productionFiles(c){return (c.files||[]).map((f,i)=>{const preview=/\.(xlsx|xls|xlsm|xlsb|pdf)$/i.test(f.name);return `<div class="correction-file"><span>${esc(f.name)}</span><div>${preview?`<button class="preview-button" data-kind="correction" data-id="${esc(c.id)}" data-index="${i}" data-name="${esc(f.name)}">Visualizar</button>`:''}<a href="/correction-file?id=${encodeURIComponent(c.id)}&index=${i}&mode=download">↓ Baixar original · ${Math.ceil(f.size/1024)} KB</a></div></div>`;}).join('');}
function assistantBlock(p){const problem=[p['Descrição'],p['Obs do Lote']].filter(Boolean).join(' — '),suggestions=CorrectionKnowledge.suggest(problem),options=CorrectionKnowledge.actions.map(a=>`<option value="${a.id}">${esc(a.family)} · ${esc(a.name)}</option>`).join('');return `<section class="smart-assistant" data-problem="${esc(problem)}"><div class="assistant-title"><div><span>✦ ASSISTENTE DE CORREÇÃO</span><strong>Registre com mais precisão</strong></div><small>Sugestões para avaliação técnica</small></div><p class="assistant-context">Com base no apontamento: <b>${esc(problem||'descrição não informada')}</b></p><div class="suggestion-chips">${suggestions.map(a=>`<button type="button" class="suggestion-chip" data-action="${a.id}">${esc(a.name)}<small>Risco ${esc(a.risk.toLowerCase())}</small></button>`).join('')}</div><div class="assistant-fields"><label class="assistant-action">Ação realizada<select name="catalogAction"><option value="">Selecione uma ação</option>${options}</select></label><label>Furo ou região<input name="location" placeholder="Ex.: Furo 2 · lado direito"></label><label>Valor<input name="measure" inputmode="decimal" placeholder="Ex.: 0,20"></label><label>Unidade<select name="unit"><option value="">Sem medida</option><option>mm</option><option>graus</option><option>%</option><option>mm/m</option></select></label><label>Método<select name="method"><option value="">Selecione</option><option>Esmerilhamento</option><option>Polimento</option><option>Fresamento</option><option>Retífica</option><option>EDM</option><option>Solda</option><option>Ajuste</option><option>Limpeza</option><option>Inspeção</option><option>Outro</option></select></label><label class="custom-action" hidden>Correção personalizada<input name="customAction" placeholder="Descreva a ação realizada"></label></div><div class="assistant-guidance" hidden></div><button type="button" class="build-description" disabled>Usar descrição sugerida</button></section>`;}
window.renderCorrections=function(){
 const all=(data.productionNotes?.length?data.productionNotes:data.corrections)||[],search=$('corrections-search')?.value.trim().toLocaleUpperCase('pt-BR')||'',selected=$('corrections-tool')?.value||'';
 const sequenceMap=new Map();
 for(const r of data.records||[]){const key=sequenceKey(r.tool,r.sequence);if(!r.tool||key.endsWith('|'))continue;if(!sequenceMap.has(key))sequenceMap.set(key,{tool:r.tool,sequence:seqNumber(r.sequence),count:0});}
 for(const c of all){const key=sequenceKey(c.tool,c.sequence);if(!sequenceMap.has(key))sequenceMap.set(key,{tool:c.tool,sequence:seqNumber(c.sequence),count:0});sequenceMap.get(key).count++;}
 const sequences=[...sequenceMap.entries()].sort((a,b)=>a[1].tool.localeCompare(b[1].tool,'pt-BR',{numeric:true})||a[1].sequence-b[1].sequence);
 if($('corrections-tool')){$('corrections-tool').innerHTML='<option value="">Todas as sequências</option>'+sequences.map(([key,s])=>`<option value="${esc(key)}">${esc(sequenceLabel(s.tool,s.sequence))} · ${s.count} apontamento(s)</option>`).join('');$('corrections-tool').value=productionSequenceFilter;if($('corrections-tool').value!==productionSequenceFilter){productionSequenceFilter='';$('corrections-tool').value='';}}
 const rows=all.filter(c=>{const p=c.payload||{},key=sequenceKey(c.tool,c.sequence),hay=[c.tool,c.sequence,p['Descrição'],p['Obs do Lote'],p['Correção Efetuada'],p['Corretor']].join(' ').toLocaleUpperCase('pt-BR');return(!selected||key===selected)&&(!search||hay.includes(search));}).sort((a,b)=>(Number(b.payload?.Data)||0)-(Number(a.payload?.Data)||0));
 const chosen=sequenceMap.get(selected);$('corrections-count').textContent=selected?`${rows.length} apontamento(s) em ${sequenceLabel(chosen?.tool||'',chosen?.sequence)}`:`${rows.length} apontamento(s)`;
 const alignment=selected&&chosen?`<div class="sequence-alignment"><strong>${esc(sequenceLabel(chosen.tool,chosen.sequence))}</strong><span>${rows.length?`${rows.length} apontamento(s) vinculado(s) exatamente a esta sequência.`:'Nenhum apontamento de produção vinculado a esta sequência.'}</span></div>`:'';
 $('corrections-list').innerHTML=alignment+(rows.map(c=>{const p=c.payload||{},correction=c.correction_text||p['Correção Efetuada'],editor=typeof authUser!=='undefined'&&authUser?`<form class="correction-editor" data-id="${esc(c.id)}">${assistantBlock(p)}<label>Descrição final da correção<textarea name="text" maxlength="10000" placeholder="Selecione uma ação acima ou descreva a correção executada">${esc(correction||'')}</textarea></label><label>Anexar Excel ou PDF<input name="file" type="file" accept=".xlsx,.xls,.xlsm,.xlsb,.pdf"></label><small>Máximo de 25 MB por arquivo.</small><div><span class="save-status" role="status"></span><button type="submit">Salvar correção</button></div></form>`:`<p class="login-hint">Faça login no botão “Atualizar e-mails” para adicionar observações e arquivos.</p>`;return `<article class="correction-card ${expandedCorrectionIds.has(c.id)?'expanded':''}"><div class="correction-head"><div><span class="eyebrow">${esc(sequenceLabel(c.tool,c.sequence))}</span><h3>${esc(p['Descrição']||'Apontamento sem descrição')}</h3></div><strong>Apontamento ${esc(p['Nr.Correção']??'—')}</strong></div><div class="correction-grid"><div><span>Data da produção</span><strong>${esc(excelDate(p['Data']))}</strong></div><div><span>Lote</span><strong>${esc(p['Lote']??'—')}</strong></div><div><span>Corretor</span><strong>${esc(p['Corretor']||'—')}</strong></div><div><span>Inspetor</span><strong>${esc(p['Inspetor']||'—')}</strong></div></div><section class="production-note"><strong>Apontamento de produção</strong><p>${esc(p['Obs do Lote']||'Não informado.')}</p></section><section class="correction-result ${correction?'completed':'pending'}"><div><strong>Correção executada</strong><span>${correction?'Registrada':'Pendente'}</span></div><p>${esc(correction||'Aguardando o registro da correção executada.')}</p>${c.corrected_by_name?`<small>Registrada por ${esc(c.corrected_by_name)} em ${esc(stamp(c.corrected_at))}</small>`:''}</section>${productionFiles(c)||'<p class="meta attachment-empty">Nenhum Excel ou PDF anexado.</p>'}<div class="card-expanded">${editor}<details class="technical-details"><summary>Informações técnicas</summary><div class="technical-data">${technicalGrid(p)}</div></details></div><button type="button" class="card-toggle" data-id="${esc(c.id)}" aria-expanded="${expandedCorrectionIds.has(c.id)}">${expandedCorrectionIds.has(c.id)?'Recolher':'Ver detalhes'}</button></article>`;}).join('')||(selected?'<div class="empty">Esta ferramenta e sequência existem no histórico de testes, mas ainda não possuem apontamentos de produção.</div>':'<div class="empty">Nenhum apontamento encontrado para os filtros selecionados.</div>'));
};
function updateCorrectionAssistant(form){const assistant=form.querySelector('.smart-assistant'),id=form.elements.catalogAction.value,action=CorrectionKnowledge.byId(id),custom=id==='outro';assistant.querySelector('.custom-action').hidden=!custom;const guidance=assistant.querySelector('.assistant-guidance'),button=assistant.querySelector('.build-description');button.disabled=!action;assistant.querySelectorAll('.suggestion-chip').forEach(chip=>chip.classList.toggle('selected',chip.dataset.action===id));if(!action){guidance.hidden=true;return;}const caution=['Alto','Crítico'].includes(action.risk)?' Confirme processo, alinhamento e apoio antes de executar uma alteração irreversível.':' Confirme a região e registre a condição encontrada.';guidance.hidden=false;guidance.className=`assistant-guidance risk-${action.risk.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}`;guidance.innerHTML=`<strong>Objetivo: ${esc(action.effect)}</strong><span>Risco ${esc(action.risk)}.${esc(caution)}</span>`;}
document.addEventListener('change',event=>{const form=event.target.closest('.correction-editor');if(!form)return;if(event.target.name==='catalogAction')updateCorrectionAssistant(form);});
document.addEventListener('click',event=>{const chip=event.target.closest('.suggestion-chip');if(chip){const form=chip.closest('.correction-editor');form.elements.catalogAction.value=chip.dataset.action;updateCorrectionAssistant(form);return;}const build=event.target.closest('.build-description');if(!build)return;const form=build.closest('.correction-editor'),id=form.elements.catalogAction.value,action=CorrectionKnowledge.byId(id),location=form.elements.location.value.trim(),measure=form.elements.measure.value.trim(),unit=form.elements.unit.value,method=form.elements.method.value,custom=form.elements.customAction.value.trim();if(!action)return;if(measure&&!unit){form.elements.unit.focus();build.textContent='Selecione a unidade';setTimeout(()=>build.textContent='Usar descrição sugerida',1800);return;}if(id==='outro'&&!custom){form.elements.customAction.focus();return;}const phrase=id==='outro'?custom:action.phrase,parts=[phrase+(measure?` de ${measure} ${unit}`:''),location?`em ${location}`:'',method?`por ${method.toLowerCase()}`:''].filter(Boolean);let description=parts.join(', ')+`.`;if(id!=='outro')description+=` Objetivo: ${action.effect}.`;const textarea=form.elements.text;textarea.value=textarea.value.trim()?`${textarea.value.trim()}\n${description}`:description;textarea.focus();textarea.setSelectionRange(textarea.value.length,textarea.value.length);});
async function filePayload(file){if(!file)return null;if(file.size>25*1024*1024)throw Error('O arquivo deve ter até 25 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file);});return {name:file.name,data};}
document.addEventListener('submit',async event=>{const form=event.target.closest('.correction-editor');if(!form)return;event.preventDefault();const button=form.querySelector('button'),status=form.querySelector('.save-status');button.disabled=true;status.textContent='Salvando…';try{const file=form.elements.file.files[0],response=await fetch('/api/correction',{method:'POST',headers:{'Content-Type':'application/json','X-Painel':'local'},body:JSON.stringify({id:form.dataset.id,text:form.elements.text.value,file:await filePayload(file)})}),result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível salvar.');data=await(await fetch('/api/data')).json();status.textContent='Correção salva.';window.renderCorrections();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
document.addEventListener('click',event=>{const button=event.target.closest('.card-toggle');if(!button)return;const card=button.closest('.correction-card'),expanded=card.classList.toggle('expanded');if(expanded)expandedCorrectionIds.add(button.dataset.id);else expandedCorrectionIds.delete(button.dataset.id);button.setAttribute('aria-expanded',expanded);button.textContent=expanded?'Recolher':'Ver detalhes';});
document.querySelectorAll('.nav-button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===button));const page=button.dataset.page;$('tracking-page').hidden=page!=='tracking';$('corrections-page').hidden=page!=='corrections';$('indicators-page').hidden=page!=='indicators';if(page==='corrections')window.renderCorrections();if(page==='indicators')window.renderIndicators?.();});
$('corrections-search').oninput=()=>window.renderCorrections();
$('corrections-tool').onchange=()=>{productionSequenceFilter=$('corrections-tool').value;window.renderCorrections();};
