let productionSequenceFilter='';
function excelDate(value){if(typeof value==='number'){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return d.toLocaleDateString('pt-BR',{timeZone:'UTC'});}return value?String(value):'Data não informada';}
function seqNumber(value){const n=Number(String(value??'').replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:null;}
function sequenceKey(tool,sequence){const n=seqNumber(sequence);return `${String(tool||'').toUpperCase()}|${n??''}`;}
function sequenceLabel(tool,sequence){const n=seqNumber(sequence);return `${tool} · SEQ. ${n==null?'—':String(n).padStart(2,'0')}`;}
function productionFiles(c){return (c.files||[]).map((f,i)=>{const media=/^(video\/|application\/pdf$)/i.test(f.mimeType);return `<div class="correction-file"><span>${esc(f.name)}</span><div>${media?`<a target="_blank" rel="noopener" href="/correction-file?id=${encodeURIComponent(c.id)}&index=${i}&mode=inline">Visualizar</a>`:''}<a href="/correction-file?id=${encodeURIComponent(c.id)}&index=${i}&mode=download">Baixar · ${Math.ceil(f.size/1024)} KB</a></div></div>`;}).join('');}
window.renderCorrections=function(){
 const all=(data.productionNotes?.length?data.productionNotes:data.corrections)||[],search=$('corrections-search')?.value.trim().toLocaleUpperCase('pt-BR')||'',selected=$('corrections-tool')?.value||'';
 const sequenceMap=new Map();
 for(const r of data.records||[]){const key=sequenceKey(r.tool,r.sequence);if(!r.tool||key.endsWith('|'))continue;if(!sequenceMap.has(key))sequenceMap.set(key,{tool:r.tool,sequence:seqNumber(r.sequence),count:0});}
 for(const c of all){const key=sequenceKey(c.tool,c.sequence);if(!sequenceMap.has(key))sequenceMap.set(key,{tool:c.tool,sequence:seqNumber(c.sequence),count:0});sequenceMap.get(key).count++;}
 const sequences=[...sequenceMap.entries()].sort((a,b)=>a[1].tool.localeCompare(b[1].tool,'pt-BR',{numeric:true})||a[1].sequence-b[1].sequence);
 if($('corrections-tool')){$('corrections-tool').innerHTML='<option value="">Todas as sequências</option>'+sequences.map(([key,s])=>`<option value="${esc(key)}">${esc(sequenceLabel(s.tool,s.sequence))} · ${s.count} apontamento(s)</option>`).join('');$('corrections-tool').value=productionSequenceFilter;if($('corrections-tool').value!==productionSequenceFilter){productionSequenceFilter='';$('corrections-tool').value='';}}
 const rows=all.filter(c=>{const p=c.payload||{},key=sequenceKey(c.tool,c.sequence),hay=[c.tool,c.sequence,p['Descrição'],p['Obs do Lote'],p['Correção Efetuada'],p['Corretor']].join(' ').toLocaleUpperCase('pt-BR');return(!selected||key===selected)&&(!search||hay.includes(search));}).sort((a,b)=>(Number(b.payload?.Data)||0)-(Number(a.payload?.Data)||0));
 const chosen=sequenceMap.get(selected);$('corrections-count').textContent=selected?`${rows.length} apontamento(s) em ${sequenceLabel(chosen?.tool||'',chosen?.sequence)}`:`${rows.length} apontamento(s)`;
 const alignment=selected&&chosen?`<div class="sequence-alignment"><strong>${esc(sequenceLabel(chosen.tool,chosen.sequence))}</strong><span>${rows.length?`${rows.length} apontamento(s) vinculado(s) exatamente a esta sequência.`:'Nenhum apontamento de produção vinculado a esta sequência.'}</span></div>`:'';
 $('corrections-list').innerHTML=alignment+(rows.map(c=>{const p=c.payload||{},correction=p['Correção Efetuada'];return `<article class="correction-card"><div class="correction-head"><div><span class="eyebrow">${esc(sequenceLabel(c.tool,c.sequence))}</span><h3>${esc(p['Descrição']||'Apontamento sem descrição')}</h3></div><strong>Apontamento ${esc(p['Nr.Correção']??'—')}</strong></div><div class="correction-grid"><div><span>Data da produção</span><strong>${esc(excelDate(p['Data']))}</strong></div><div><span>Lote</span><strong>${esc(p['Lote']??'—')}</strong></div><div><span>Corretor</span><strong>${esc(p['Corretor']||'—')}</strong></div><div><span>Inspetor</span><strong>${esc(p['Inspetor']||'—')}</strong></div></div><div class="correction-text"><strong>Apontamento de produção</strong><p>${esc(p['Obs do Lote']||'Não informado.')}</p><strong>Correção executada</strong><p class="${correction?'':'pending-correction'}">${esc(correction||'Pendente de registro.')}</p></div>${productionFiles(c)||'<p class="meta">Nenhum Excel, PDF ou vídeo anexado a este apontamento.</p>'}<details><summary>Ver dados técnicos</summary><div class="technical-data">${Object.entries(p).filter(([k])=>!['Descrição','Obs do Lote','Correção Efetuada'].includes(k)).map(([k,v])=>`<span>${esc(k)}</span><strong>${esc(v??'')}</strong>`).join('')}</div></details></article>`;}).join('')||(selected?'<div class="empty">Esta ferramenta e sequência existem no histórico de testes, mas ainda não possuem apontamentos de produção.</div>':'<div class="empty">Nenhum apontamento encontrado para os filtros selecionados.</div>'));
};
document.querySelectorAll('.nav-button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===button));const corrections=button.dataset.page==='corrections';$('tracking-page').hidden=corrections;$('corrections-page').hidden=!corrections;if(corrections)window.renderCorrections();});
$('corrections-search').oninput=()=>window.renderCorrections();
$('corrections-tool').onchange=()=>{productionSequenceFilter=$('corrections-tool').value;window.renderCorrections();};
