(()=>{
 const d=id=>document.getElementById(id);let current=null,selectedFile=null,previewUrl=null,drawingPath=null;
 const cloudMode=!['localhost','127.0.0.1'].includes(location.hostname);
 const nativeFetch=window.fetch.bind(window);const localApi=(url,options={})=>{if(String(url).startsWith('/api/control-profiles'))options={...options,headers:{...(options.headers||{}),'X-Painel':'local'}};return nativeFetch(url,options)};
 const preview=document.createElement('details');preview.className='draw2data-preview';preview.innerHTML='<summary>Conferir desenho original</summary><iframe title="Desenho original para conferência" style="width:100%;height:640px;border:0"></iframe>';d('draw2data-editor').append(preview);
 const inspector=document.createElement('section');inspector.className='draw2data-inspector draw2data-inspector-float';inspector.hidden=true;inspector.innerHTML='<div class="draw2data-inspector-head" data-snapshot-drag><div><span>CONFERÊNCIA VISUAL · ARRASTE PARA MOVER</span><strong>Cota em destaque</strong><small></small></div><div><button type="button" class="secondary" data-snapshot-full>Ver PDF completo</button><button type="button" class="secondary" data-snapshot-close>Fechar</button></div></div><div class="draw2data-inspector-image" aria-live="polite"><p>Gerando recorte do desenho…</p></div>';document.body.append(inspector);
 const dragHandle=inspector.querySelector('[data-snapshot-drag]');let dragState=null;function placeInspector(){if(inspector.dataset.positioned)return;const width=Math.min(680,window.innerWidth-24);inspector.style.left=`${Math.max(12,Math.round((window.innerWidth-width)/2))}px`;inspector.style.top=`${Math.max(12,Math.round((window.innerHeight-520)/2))}px`;inspector.dataset.positioned='true'}function moveInspector(clientX,clientY){if(!dragState)return;const rect=inspector.getBoundingClientRect(),left=Math.max(8,Math.min(window.innerWidth-rect.width-8,clientX-dragState.x)),top=Math.max(8,Math.min(window.innerHeight-rect.height-8,clientY-dragState.y));inspector.style.left=`${left}px`;inspector.style.top=`${top}px`}dragHandle.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;const rect=inspector.getBoundingClientRect();dragState={x:event.clientX-rect.left,y:event.clientY-rect.top};dragHandle.setPointerCapture(event.pointerId);inspector.classList.add('is-dragging')});dragHandle.addEventListener('pointermove',event=>moveInspector(event.clientX,event.clientY));dragHandle.addEventListener('pointerup',event=>{dragState=null;inspector.classList.remove('is-dragging');if(dragHandle.hasPointerCapture(event.pointerId))dragHandle.releasePointerCapture(event.pointerId)});dragHandle.addEventListener('pointercancel',()=>{dragState=null;inspector.classList.remove('is-dragging')});
 d('draw2data-results').closest('table').querySelector('thead tr').innerHTML='<th>Status</th><th>Texto original</th><th>Nominal</th><th>Tol. +</th><th>Tol. −</th><th>Valor menor</th><th>Valor maior</th><th>Confiança</th><th>Ações</th>';
 const loader=document.createElement('div');loader.className='draw2data-scanner';loader.setAttribute('role','status');loader.setAttribute('aria-live','polite');loader.innerHTML='<div class="draw2data-scanner-art" aria-hidden="true"><span class="scanner-ring ring-one"></span><span class="scanner-ring ring-two"></span><span class="scanner-orbit orbit-one"></span><span class="scanner-orbit orbit-two"></span><span class="scanner-core">±</span><i class="scanner-node node-one"></i><i class="scanner-node node-two"></i><i class="scanner-node node-three"></i></div><div><strong class="draw2data-scanner-title">Mapeando o desenho</strong><small class="draw2data-scanner-detail">Preparando a leitura técnica…</small></div>';
 d('draw2data-status').after(loader);let loaderTimer=null;
 const saveProfile=document.createElement('button');saveProfile.type='button';saveProfile.className='secondary';saveProfile.textContent='Salvar como perfil de controle';d('draw2data-export').before(saveProfile);
 function showScanner(){const messages=['Mapeando o desenho','Separando textos e cotas','Reconhecendo símbolos de tolerância','Validando limites de qualidade'];let index=0;loader.hidden=false;loader.querySelector('.draw2data-scanner-title').textContent=messages[0];loaderTimer=setInterval(()=>{index=(index+1)%messages.length;loader.querySelector('.draw2data-scanner-title').textContent=messages[index];},1800)}
 function hideScanner(){loader.hidden=true;if(loaderTimer){clearInterval(loaderTimer);loaderTimer=null}}
 saveProfile.onclick=async()=>{if(!current?.dimensions?.length)return;const name=window.prompt('Nome do perfil de controle',`${current.tool} - Perfil dimensional`);if(name===null)return;saveProfile.disabled=true;try{const fileData=!cloudMode&&selectedFile?Array.from(new Uint8Array(await selectedFile.arrayBuffer())):[];const response=await localApi('/api/control-profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool:current.tool,name,sequence:null,revision:'00',dimensions:current.dimensions,fileData,drawingPath:cloudMode?drawingPath:null})});if(!response.ok)throw Error((await response.json()).error||'Não foi possível salvar o perfil.');d('draw2data-status').textContent='Perfil de controle salvo com o desenho original. Abra a aba Controle Dimensional para iniciar medições.';}catch(error){d('draw2data-status').textContent=error.message;}finally{saveProfile.disabled=false}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=value=>{if(value==null||value==='')return '';const n=Number(value);if(!Number.isFinite(n))return '';return n.toFixed(6).replace(/0+$/,'').replace(/\.$/,'').replace('.',',')};
 async function showSnapshot(index){
  const item=current?.dimensions?.[index];if(!item||!selectedFile)return;
  const hasLocation=[item.x,item.y,item.width,item.height].every(value=>Number.isFinite(Number(value)))&&Number(item.width)>0&&Number(item.height)>0;
  if(!hasLocation){d('draw2data-status').textContent='Esta cota foi adicionada manualmente e não possui uma posição no desenho.';return;}
  inspector.hidden=false;placeInspector();const title=inspector.querySelector('strong'),subtitle=inspector.querySelector('small'),image=inspector.querySelector('.draw2data-inspector-image');title.textContent=`Cota ${fmt(item.nominal)}${item.tolerancePlus==null?'':` ± ${fmt(item.tolerancePlus)}`}`;subtitle.textContent=`Página ${item.page} · a moldura vermelha indica a posição lida pelo motor.`;image.innerHTML='<p>Gerando recorte do desenho…</p>';
  try{const payload=cloudMode?{path:drawingPath,dimension:item}:{fileName:selectedFile.name,data:Array.from(new Uint8Array(await selectedFile.arrayBuffer())),dimension:item},response=await fetch('/api/draw2data/snapshot',{method:'POST',headers:{'Content-Type':'application/json','X-Painel':'local'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível gerar o recorte.');image.innerHTML='';const picture=document.createElement('img');picture.src=`data:image/png;base64,${result.data}`;picture.alt=`Recorte da página ${result.page} com a cota ${item.rawText} destacada`;image.append(picture);}catch(error){image.innerHTML=`<p>${esc(error.message)}</p>`;}
 }
 inspector.querySelector('[data-snapshot-close]').onclick=()=>{inspector.hidden=true};inspector.querySelector('[data-snapshot-full]').onclick=()=>{preview.open=true;preview.scrollIntoView({behavior:'smooth',block:'start'})};
 function render(){
  const list=d('draw2data-results'),count=d('draw2data-count');if(!current){list.innerHTML='<tr><td colspan="7"><div class="empty">Selecione um PDF para iniciar a análise.</div></td></tr>';count.textContent='';return;}
  d('draw2data-tool').textContent=current.tool;d('draw2data-file').textContent=current.fileName;d('draw2data-method').textContent=current.method;d('draw2data-page-count').textContent=current.pageCount;count.textContent=`${current.dimensions.length} cota(s)`;
  d('draw2data-warnings').innerHTML=(current.warnings||[]).map(w=>`<div class="draw2data-warning">${esc(w)}</div>`).join('');
  list.innerHTML=current.dimensions.map((item,index)=>{const n=Number(item.nominal),p=item.tolerancePlus==null||item.tolerancePlus===''?null:Number(item.tolerancePlus),m=item.toleranceMinus==null||item.toleranceMinus===''?null:Number(item.toleranceMinus),located=[item.x,item.y,item.width,item.height].every(value=>Number.isFinite(Number(value)))&&Number(item.width)>0&&Number(item.height)>0;return `<tr data-dimension="${index}"><td><select data-field="status"><option value="CONFIRMADO" ${item.status==='CONFIRMADO'?'selected':''}>Confirmado</option><option value="REVISAR" ${item.status==='REVISAR'?'selected':''}>Revisar</option><option value="IGNORADO" ${item.status==='IGNORADO'?'selected':''}>Ignorado</option></select></td><td><input data-field="rawText" value="${esc(item.rawText)}"></td><td><input data-field="nominal" value="${esc(fmt(item.nominal))}" inputmode="decimal"></td><td><input data-field="tolerancePlus" value="${esc(fmt(item.tolerancePlus))}" inputmode="decimal"></td><td><input data-field="toleranceMinus" value="${esc(fmt(item.toleranceMinus))}" inputmode="decimal"></td><td class="draw2data-derived">${m===null?'':esc(fmt(n-m))}</td><td class="draw2data-derived">${p===null?'':esc(fmt(n+p))}</td><td>${esc(`${Math.round(item.confidence*100)}%`)}</td><td class="draw2data-row-actions"><button type="button" class="secondary draw2data-snapshot" data-index="${index}" ${located?'':'disabled'}>Ver no desenho</button><button type="button" class="secondary draw2data-delete" data-index="${index}">Excluir</button></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty">Nenhuma cota foi identificada automaticamente. Confira o aviso acima ou adicione uma cota manualmente.</div></td></tr>';
  d('draw2data-empty').hidden=true;d('draw2data-editor').hidden=false;
  d('draw2data-export').disabled=!current.dimensions.length;
  for(const row of list.querySelectorAll('tr[data-dimension]')){const item=current.dimensions[Number(row.dataset.dimension)];if(item.reviewReason){const note=document.createElement('small');note.textContent=item.reviewReason;note.style.display='block';row.cells[1].append(note);}}
 }
 async function uploadDrawing(file){const ticket=await fetch('/api/draw2data/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({size:file.size,mimeType:file.type||'application/pdf'})}),meta=await ticket.json();if(!ticket.ok)throw Error(meta.error||'Não foi possível preparar o envio do PDF.');const upload=await fetch(meta.uploadUrl,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:file});if(!upload.ok)throw Error('Não foi possível enviar o PDF para análise. Tente novamente.');return meta.path;}
 async function analyze(file){
  if(file.size>25*1024*1024){d('draw2data-status').textContent='Selecione um PDF de até 25 MB.';return;}
  d('draw2data-status').textContent='Enviando o PDF para a leitura técnica…';showScanner();d('draw2data-analyze').disabled=true;d('draw2data-empty-action').disabled=true;d('draw2data-export').disabled=true;
  try{const payload=cloudMode?{fileName:file.name,path:await uploadDrawing(file)}:{fileName:file.name,data:Array.from(new Uint8Array(await file.arrayBuffer()))},response=await fetch('/api/draw2data/analyze',{method:'POST',headers:{'Content-Type':'application/json','X-Painel':'local'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível analisar o PDF.');current=result;selectedFile=file;drawingPath=cloudMode?payload.path:null;inspector.hidden=true;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);preview.querySelector('iframe').src=previewUrl;render();d('draw2data-status').textContent=result.dimensions.length?`Leitura concluída: ${result.dimensions.length} cota(s). Confira os itens marcados para revisão.`:'Leitura concluída sem cotas. Consulte o diagnóstico abaixo.';}catch(error){d('draw2data-status').textContent=error.message;}finally{hideScanner();d('draw2data-analyze').disabled=false;d('draw2data-empty-action').disabled=false;d('draw2data-file-input').value='';}}
 d('draw2data-analyze').onclick=()=>d('draw2data-file-input').click();d('draw2data-empty-action').onclick=()=>d('draw2data-file-input').click();d('draw2data-config').onclick=()=>{d('draw2data-status').textContent='As configurações avançadas serão liberadas nas próximas fases.'};d('draw2data-file-input').onchange=()=>{const file=d('draw2data-file-input').files[0];if(file)analyze(file)};
 d('draw2data-add').onclick=()=>{if(!current)return;current.dimensions.push({id:`manual-${Date.now()}`,rawText:'',nominal:'',tolerancePlus:'',toleranceMinus:'',page:1,x:0,y:0,confidence:1,source:'MANUAL',status:'REVISAR'});render()};
 d('draw2data-results').addEventListener('input',event=>{const row=event.target.closest('tr[data-dimension]');if(!row||!current)return;const item=current.dimensions[Number(row.dataset.dimension)],field=event.target.dataset.field;if(field==='rawText'||field==='status')item[field]=event.target.value;else item[field]=event.target.value===''?'':Number(String(event.target.value).replace(',','.'))});
 d('draw2data-results').addEventListener('click',event=>{const snapshot=event.target.closest('.draw2data-snapshot');if(snapshot){showSnapshot(Number(snapshot.dataset.index));return;}const button=event.target.closest('.draw2data-delete');if(button){current.dimensions.splice(Number(button.dataset.index),1);render()}});
 d('draw2data-export').onclick=async()=>{if(!current||!selectedFile)return;const button=d('draw2data-export');button.disabled=true;button.textContent='Gerando Excel…';try{const response=await fetch('/api/draw2data/export',{method:'POST',headers:{'Content-Type':'application/json','X-Painel':'local'},body:JSON.stringify(current)}),result=await response.json();if(!response.ok)throw Error(result.error||'Não foi possível gerar o Excel.');const bytes=Uint8Array.from(atob(result.data),char=>char.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a');link.href=url;link.download=result.fileName;link.click();URL.revokeObjectURL(url);d('draw2data-status').textContent=`Excel gerado: ${result.fileName}`}catch(error){d('draw2data-status').textContent=error.message}finally{button.disabled=false;button.textContent='Gerar Excel'}};
 render();
})();
