const crypto=require('crypto'),path=require('path');
const {parseCorrections}=require('../importer.cjs');
const {processDrawing}=require('../draw2data/processing.cjs');
const {renderDimensionSnapshot}=require('../draw2data/snapshot.cjs');
const {exportBytes}=require('../draw2data/exporter.cjs');
const endpoint=process.env.QUALITY_COLLECTOR_ENDPOINT,collectorToken=process.env.QUALITY_COLLECTOR_TOKEN,sessionSecret=process.env.QUALITY_SESSION_SECRET;
function send(res,code,body,headers={}){res.statusCode=code;Object.entries(headers).forEach(([k,v])=>res.setHeader(k,v));if(Buffer.isBuffer(body))return res.end(body);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function configured(){return endpoint&&collectorToken&&sessionSecret?.length>=32;}
async function collector(action,{method='GET',body,type='application/json',object,query}={}){if(!configured())throw Error('Configuração do serviço incompleta.');const url=new URL(endpoint);url.searchParams.set('action',action);if(object)url.searchParams.set('path',object);for(const [key,value] of Object.entries(query||{}))if(value!==undefined&&value!==null)url.searchParams.set(key,String(value));const response=await fetch(url,{method,headers:{'x-collector-token':collectorToken,'Content-Type':type},body});if(!response.ok){const detail=(await response.text()).slice(0,300);if(action==='import-production'&&response.status===404)throw Error('A importação de produção ainda não foi publicada no serviço de dados. A função e as tabelas do Supabase precisam ser atualizadas antes de importar.');throw Error(`Serviço de dados (${response.status}): ${detail}`);}return response;}
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(v=>v.length===2));
function sign(user){const payload=Buffer.from(JSON.stringify({user,expires:Date.now()+28800000})).toString('base64url'),signature=crypto.createHmac('sha256',sessionSecret).update(payload).digest('base64url');return `${payload}.${signature}`;}
function auth(req){try{const [payload,signature]=String(cookies(req).quality_session||'').split('.'),expected=crypto.createHmac('sha256',sessionSecret).update(payload).digest(),actual=Buffer.from(signature,'base64url');if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;const value=JSON.parse(Buffer.from(payload,'base64url'));return value.expires>Date.now()?value.user:null;}catch{return null;}}
async function input(req,limit=36*1024*1024){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>limit)throw Error('Requisição muito grande.');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString()||'{}');}
function checkedFile(file){if(!file)return null;const name=path.basename(String(file.name||'')),ext=path.extname(name).toLowerCase();if(!['.xlsx','.xls','.xlsm','.xlsb','.pdf'].includes(ext))throw Error('Selecione um arquivo Excel ou PDF.');const bytes=Buffer.from(String(file.data||''),'base64');if(!bytes.length||bytes.length>25*1024*1024)throw Error('O arquivo deve ter até 25 MB.');const pdf=bytes.subarray(0,5).toString()==='%PDF-',zip=bytes[0]===80&&bytes[1]===75,ole=bytes.subarray(0,8).equals(Buffer.from([208,207,17,224,161,177,26,225]));if(ext==='.pdf'?!pdf:!(zip||ole))throw Error('O conteúdo do arquivo não corresponde ao formato selecionado.');return {name,bytes,mimeType:ext==='.pdf'?'application/pdf':ext==='.xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'application/vnd.ms-excel'};}
function checkedDrawing(file){const result=checkedFile(file);if(!result||result.mimeType!=='application/pdf')throw Error('Selecione o desenho técnico em PDF.');return result;}
const getData=async(includeProduction=false)=>(await collector('data',{query:includeProduction?{includeProduction:1}:undefined})).json();
async function validateLocation(correctionId,location){if(!location)return;const all=await getData(true),correction=(all.productionNotes||all.corrections||[]).find(c=>c.id===correctionId);if(!correction)throw Error('Apontamento não encontrado.');if(location.remove){if(!(correction.locations||[]).some(l=>l.id===location.id))throw Error('Localização não pertence a esta correção.');return;}const drawing=(all.toolDrawings||[]).find(d=>d.id===location.drawingId);if(!drawing||String(drawing.tool).toUpperCase()!==String(correction.tool).toUpperCase()||(drawing.sequence!=null&&Number(drawing.sequence)!==Number(correction.sequence)))throw Error('O desenho não pertence a esta ferramenta e sequência.');}
async function storedFile(req,res,kind){const url=new URL(req.url,'https://app.local'),all=await getData(kind==='correction'),id=url.searchParams.get('id'),index=Number(url.searchParams.get('index'));const item=kind==='test'?all.records?.find(r=>r.id===id)?.attachments?.[index]:(all.productionNotes||all.corrections||[]).find(r=>r.id===id)?.files?.[index],object=item?.cloudPath||item?.objectPath;if(!object)return send(res,404,{error:'Arquivo não encontrado.'});const response=await collector('file',{object}),bytes=Buffer.from(await response.arrayBuffer()),canInline=/^(video\/|application\/pdf$)/i.test(item.mimeType||'')||/\.pdf$/i.test(item.name||''),inline=url.searchParams.get('mode')==='inline'&&canInline;send(res,200,bytes,{'Content-Type':response.headers.get('content-type')||item.mimeType||(/\.pdf$/i.test(item.name||'')?'application/pdf':'application/octet-stream'),'Content-Disposition':`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(item.name)}`,'Cache-Control':'private, no-store'});}
const controlObject=value=>/^control-drawings\/[0-9a-f-]{36}\.pdf$/i.test(String(value||''))||/^control-evidence\/[0-9a-f-]{36}\/[0-9a-f-]{36}\.(jpg|png|webp)$/i.test(String(value||''));
async function controlFile(object){if(!controlObject(object))throw Error('Arquivo de controle inválido.');const response=await collector('file',{object});return Buffer.from(await response.arrayBuffer());}
function inspectionReport(inspection){const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),num=value=>Number.isFinite(Number(value))?Number(value).toLocaleString('pt-BR',{maximumFractionDigits:4}):'—',failed=(inspection.measurements||[]).some(item=>item.result==='REPROVADO'),rows=(inspection.measurements||[]).map(item=>{const low=item.toleranceMinus==null?'REF':`${num(Number(item.nominal)-Number(item.toleranceMinus))} – ${num(Number(item.nominal)+Number(item.tolerancePlus))}`;return `<tr><td>${esc(item.item||'—')}</td><td>${esc(item.sample||'—')}</td><td>${num(item.nominal)}</td><td>${low}</td><td>${num(item.value)}</td><td class="${item.result==='REPROVADO'?'fail':'ok'}">${esc(item.result||'REGISTRADO')}</td></tr>`}).join('');return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Relatório dimensional ${esc(inspection.tool)}</title><style>body{font-family:Arial,sans-serif;color:#142c42;margin:36px}.brand{color:#087f78;font-weight:800;letter-spacing:2px}.status{float:right;padding:8px 12px;background:${failed?'#fde8e8':'#e5f6f1'};font-weight:bold}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.meta div{padding:10px;background:#f5f8f9}.meta b{display:block;font-size:11px;color:#587082}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:8px;border:1px solid #d7e1e5;text-align:left}th{background:#eaf3f2}.ok{color:#087f78}.fail{color:#b42318;font-weight:bold}</style><body><span class="status">${failed?'REPROVADO':'REGISTRADO'}</span><div class="brand">TECNOPERFIL · QUALIDADE</div><h1>Relatório dimensional de inspeção</h1><div class="meta"><div><b>Ferramenta</b>${esc(inspection.tool)}</div><div><b>Data</b>${esc(inspection.date)}</div><div><b>Lote</b>${esc(inspection.lot||'—')}</div><div><b>Cliente</b>${esc(inspection.client||'—')}</div><div><b>Peça</b>${esc(inspection.part||'—')}</div><div><b>Inspetor</b>${esc(inspection.operator||'—')}</div></div><table><thead><tr><th>Item</th><th>Furo</th><th>Nominal</th><th>Limites</th><th>Medido</th><th>Resultado</th></tr></thead><tbody>${rows||'<tr><td colspan="6">Sem medições.</td></tr>'}</tbody></table><h2>Observações</h2><p>${esc(inspection.observations||'Sem observações.')}</p></body></html>`;}
module.exports=async(req,res)=>{try{const url=new URL(req.url,'https://app.local'),pathname=url.pathname;
 if(pathname==='/api/status')return send(res,200,{syncing:false,error:'',lastRun:'',canSync:false,cloud:{enabled:configured()}});
 if(pathname==='/api/data')return send(res,200,{...(await getData(url.searchParams.get('includeProduction')==='1')),dataOrigin:'cloud'});
 if(pathname==='/api/auth')return send(res,200,{user:auth(req)});
 if(pathname==='/api/login'&&req.method==='POST'){const body=await input(req,8192),result=await(await collector('login',{method:'POST',body:JSON.stringify({email:body.email,password:body.password})})).json();res.setHeader('Set-Cookie',`quality_session=${sign(result.user)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`);return send(res,200,{user:result.user});}
 if(pathname==='/api/logout'&&req.method==='POST'){res.setHeader('Set-Cookie','quality_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true});}
 if(pathname==='/api/draw2data/upload'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para analisar um desenho.'});const body=await input(req,8192),response=await collector('control-upload',{method:'POST',body:JSON.stringify({kind:'drawing',size:Number(body.size),mimeType:String(body.mimeType||'')})});return send(res,200,await response.json());}
 if(pathname==='/api/control-upload'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Faça login para enviar uma foto.'});const body=await input(req,8192),response=await collector('control-upload',{method:'POST',body:JSON.stringify({kind:'evidence',inspectionId:String(body.inspectionId||''),size:Number(body.size),mimeType:String(body.mimeType||'')})});return send(res,200,await response.json());}
 if(pathname==='/api/draw2data/analyze'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para analisar um desenho.'});const body=await input(req,32768),object=String(body.path||''),fileName=path.basename(String(body.fileName||''));if(!/^control-drawings\/[0-9a-f-]{36}\.pdf$/i.test(object)||!/\.pdf$/i.test(fileName))return send(res,400,{error:'Selecione um PDF válido.'});return send(res,200,await processDrawing(fileName,await controlFile(object)));}
 if(pathname==='/api/draw2data/snapshot'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para visualizar a cota.'});const body=await input(req,32768),object=String(body.path||'');if(!/^control-drawings\/[0-9a-f-]{36}\.pdf$/i.test(object))return send(res,400,{error:'Desenho inválido.'});const image=await renderDimensionSnapshot(await controlFile(object),body.dimension);return send(res,200,{page:image.page,width:image.width,height:image.height,data:image.bytes.toString('base64')});}
 if(pathname==='/api/draw2data/export'&&req.method==='POST'){const body=await input(req,2*1024*1024);if(!Array.isArray(body.dimensions)||body.dimensions.length>5000||!String(body.fileName||''))return send(res,400,{error:'Resultado de análise inválido.'});const result=exportBytes(body);return send(res,200,{fileName:result.fileName,data:result.bytes.toString('base64')});}
 if(pathname==='/api/control-profiles'&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Faça login para acessar os perfis de controle.'});return send(res,200,await(await collector('control-profiles')).json());}
 if(pathname==='/api/control-profiles'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para salvar o perfil.'});const body=await input(req,2*1024*1024),response=await collector('control-profiles',{method:'POST',body:JSON.stringify(body)});return send(res,201,await response.json());}
 if(pathname==='/api/control-profiles/update'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Faça login para alterar o perfil.'});const body=await input(req,2*1024*1024),response=await collector('control-profiles-update',{method:'POST',body:JSON.stringify(body)});return send(res,200,await response.json());}
 if(pathname==='/api/control-profiles/delete'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Faça login para excluir o perfil.'});const body=await input(req,32768),response=await collector('control-profiles-delete',{method:'POST',body:JSON.stringify(body)});return send(res,200,await response.json());}
 if(pathname==='/api/inspections'&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Faça login para acessar as inspeções.'});return send(res,200,await(await collector('inspections')).json());}
 if(pathname==='/api/inspections'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para salvar a inspeção.'});const body=await input(req,2*1024*1024),response=await collector('inspections',{method:'POST',body:JSON.stringify({...body,userId:user.id,userName:user.name||user.email})});return send(res,201,await response.json());}
 const inspectionReportMatch=pathname.match(/^\/api\/inspections\/([0-9a-f-]{36})\/report$/i);if(inspectionReportMatch&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Faça login para baixar o relatório.'});const inspections=await(await collector('inspections')).json(),inspection=inspections.find(item=>item.id===inspectionReportMatch[1]);if(!inspection)return send(res,404,{error:'Inspeção não encontrada.'});const name=`relatorio-dimensional-${String(inspection.tool||'perfil').replace(/[^a-z0-9_-]/gi,'-')}-${inspection.date}.html`;return send(res,200,Buffer.from(inspectionReport(inspection)),{'Content-Type':'text/html; charset=utf-8','Content-Disposition':`attachment; filename="${name}"`});}
 const controlDrawingMatch=pathname.match(/^\/api\/control-profiles\/([0-9a-f-]{36})\/drawing$/i);if(controlDrawingMatch&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Faça login para visualizar o desenho.'});const profiles=await(await collector('control-profiles')).json(),profile=profiles.find(item=>item.id===controlDrawingMatch[1]);if(!profile?.drawingPath)return send(res,404,{error:'Desenho não associado a este perfil.'});return send(res,200,await controlFile(profile.drawingPath),{'Content-Type':'application/pdf','Content-Disposition':'inline','Cache-Control':'private, max-age=60'});}
 if(pathname==='/api/correction'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para registrar a correção.'});const body=await input(req),file=checkedFile(body.file),locations=Array.isArray(body.locations)?body.locations.slice(0,50):body.location?[body.location]:[];if(!/^[0-9a-f-]{36}$/.test(String(body.id||''))||String(body.text||'').length>10000)throw Error('Dados inválidos.');for(const location of locations)await validateLocation(body.id,location);let meta=null;if(file){const ext=path.extname(file.name).toLowerCase(),object=`corrections/${body.id}/${Date.now()}-${crypto.randomBytes(5).toString('hex')}${ext}`;await collector('file',{method:'PUT',body:file.bytes,type:file.mimeType,object});meta={name:file.name,objectPath:object,size:file.bytes.length,mimeType:file.mimeType};}await collector('correction',{method:'POST',body:JSON.stringify({id:body.id,text:String(body.text||''),userId:user.id,userName:user.name||user.email,file:meta})});for(const location of locations)await collector('location',{method:'POST',body:JSON.stringify({...location,correctionId:body.id,userId:user.id,userName:user.name||user.email})});const confirmed=await getData(true),saved=((confirmed.productionNotes||confirmed.corrections||[]).find(c=>c.id===body.id)?.locations||[]),savedIds=new Set(saved.map(l=>l.id));for(const location of locations){const persisted=location.remove?!savedIds.has(location.id):savedIds.has(location.id);if(!persisted)throw Error('O banco não confirmou a gravação das marcações. Tente novamente.');}return send(res,200,{ok:true,locations:saved.length,confirmed:true});}
 if(pathname==='/api/tool-drawing'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para associar o desenho.'});const body=await input(req,14*1024*1024),file=checkedDrawing(body.file),tool=String(body.tool||'').trim().toUpperCase(),sequence=Number(body.sequence),id=crypto.randomUUID();if(!tool||!Number.isInteger(sequence)||sequence<1)throw Error('Ferramenta e sequência inválidas.');const object=`drawings/${id}/${Date.now()}-${crypto.randomBytes(5).toString('hex')}.pdf`;await collector('file',{method:'PUT',body:file.bytes,type:'application/pdf',object});const result=await(await collector('tool-drawing',{method:'POST',body:JSON.stringify({id,tool,sequence,name:file.name,objectPath:object,size:file.bytes.length,userId:user.id})})).json();return send(res,200,{ok:true,...result});}
 if(pathname==='/api/import-corrections'&&req.method==='POST'){const user=auth(req);if(!user)return send(res,401,{error:'Faça login para importar a planilha.'});const body=await input(req,16*1024*1024),bytes=Buffer.from(String(body.data||''),'base64');if(!bytes.length||bytes.length>10*1024*1024||bytes[0]!==80||bytes[1]!==75)throw Error('Selecione um arquivo Excel .xlsx de até 10 MB.');const result=await parseCorrections(bytes,await getData(true));if(body.expectedKind&&result.kind!==body.expectedKind)throw Error(body.expectedKind==='correction'?'Esta planilha não possui a coluna Correção Efetuada. Selecione a planilha de correções executadas.':'Esta planilha contém correções. Use o botão Importar correções na tela de Apontamentos.');if(body.confirm){const allRows=result.rows.filter(row=>row.status==='matched'||row.status==='new'),production=result.kind==='production',offset=Math.max(0,Number(body.offset)||0),limit=Math.min(50,Math.max(1,Number(body.limit)||25)),rows=production?allRows.slice(offset,offset+limit):allRows;await collector(production?'import-production':'import-corrections',{method:'POST',body:JSON.stringify({rows,userId:user.id,userName:user.name||user.email,importId:body.importId,totalRows:allRows.length})});result.imported=rows.length;result.totalImportable=allRows.length;result.nextOffset=production?offset+rows.length:allRows.length;result.complete=!production||result.nextOffset>=allRows.length;}return send(res,200,result);}
 if(pathname==='/api/whatsapp-settings'){if(!auth(req))return send(res,401,{error:'Faça login para configurar as notificações.'});if(req.method==='GET')return send(res,200,await(await collector('whatsapp-settings')).json());if(req.method==='POST'){const body=await input(req,32768),response=await collector('whatsapp-settings',{method:'POST',body:JSON.stringify(body)});return send(res,200,await response.json());}}
 if(pathname==='/api/whatsapp-notifications'&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Faça login para ver o histórico.'});return send(res,200,await(await collector('whatsapp-notifications')).json());}
 if(pathname==='/api/whatsapp-retry'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Faça login para reenviar a notificação.'});const body=await input(req,4096),response=await collector('whatsapp-retry',{method:'POST',body:JSON.stringify(body)});return send(res,200,await response.json());}
 if(pathname==='/api/sync')return send(res,409,{error:'A coleta de e-mails é executada pelo computador autorizado.'});
 if(pathname==='/api/preview'&&req.method==='POST'){const all=await getData(),item=all.records?.find(r=>r.id===url.searchParams.get('id'))?.attachments?.[Number(url.searchParams.get('index'))];if(url.searchParams.get('kind')==='correction')return send(res,422,{error:'Use “Baixar original” para abrir este arquivo.'});if(item?.preview)return send(res,200,{...item.preview,name:item.name});if(item&&/\.pdf$/i.test(item.name||''))return send(res,200,{name:item.name,directPdf:true});return send(res,404,{error:'Pré-visualização ainda não disponível.'});}
 if(pathname==='/attachment')return storedFile(req,res,'test');if(pathname==='/correction-file')return storedFile(req,res,'correction');
 if(pathname==='/tool-drawing'){if(!auth(req))return send(res,401,{error:'Faça login para visualizar o desenho.'});const all=await getData(),drawing=(all.toolDrawings||[]).find(d=>d.id===url.searchParams.get('id'));if(!drawing?.objectPath)return send(res,404,{error:'Desenho não encontrado.'});const response=await collector('file',{object:drawing.objectPath}),bytes=Buffer.from(await response.arrayBuffer());return send(res,200,bytes,{'Content-Type':'application/pdf','Content-Disposition':'inline','Cache-Control':'private, max-age=60'});}
 if(pathname.startsWith('/preview/')){const object=pathname.slice(1).replace(/^preview\//,'previews/');if(!/^previews\/[a-f0-9]{64}\/sheet-\d+(?:-\d+)?\.(pdf|png)$/.test(object))return send(res,404,{});const response=await collector('file',{object}),bytes=Buffer.from(await response.arrayBuffer());return send(res,200,bytes,{'Content-Type':response.headers.get('content-type')||'application/octet-stream','Cache-Control':'private, max-age=300'});}
 return send(res,404,{});
 }catch(error){send(res,500,{error:error.message||'Falha interna.'});}};
